# Generated by Django 6.0 on 2025-12-23 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be in E.164 format (+1234567890)', regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
