# Generated by Django 6.0 on 2025-12-24 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_receiver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 24, 15, 46, tzinfo=datetime.timezone.utc)),
        ),
    ]
